FROM node:20-alpine


ARG NODE_ENV=development
ARG PORT=4338
ENV PORT $PORT
RUN npm install -g pnpm@latest

USER node
WORKDIR /wms-ui
COPY --chown=node:node package.json pnpm-lock.yaml* ./
ENV PATH /wms-api/node_modules/.bin:$PATH
COPY --chown=node:node . .
RUN pnpm install
CMD ["pnpm", "start:dev"]
EXPOSE $PORT

